CREATE TABLE PAUTA (
  	CD_PAUTA NUMERIC(9) NOT NULL AUTO_INCREMENT,
  	NM_PAUTA VARCHAR(100) NOT NULL,
  	DT_CADASTRO TIMESTAMP NOT NULL,
  	DT_ABERTURA TIMESTAMP,
  	DT_ENCERRAMENTO TIMESTAMP,
  	DT_APURACAO TIMESTAMP,
  	NR_VOTOS_FAVOR NUMERIC(9),
  	NR_VOTOS_CONTRA NUMERIC(9),
  	CONSTRAINT PAUTA_PK PRIMARY KEY (CD_PAUTA)
  );

CREATE TABLE PAUTA_VOTACAO (
	CD_PAUTA_VOTACAO NUMERIC(9) NOT NULL AUTO_INCREMENT,
	DT_CADASTRO TIMESTAMP NOT NULL,
	NR_CPF_ASSOCIADO VARCHAR(11) NOT NULL,
	BL_VOTO BOOLEAN NOT NULL,
	CD_PAUTA NUMERIC(9) NOT NULL,
	CONSTRAINT PAUTA_VOTACAO_PK PRIMARY KEY (CD_PAUTA_VOTACAO),
	CONSTRAINT PAUTA_VOTACAO_UN UNIQUE (CD_PAUTA,NR_CPF_ASSOCIADO),
	CONSTRAINT PAUTA_VOTACAO_FK FOREIGN KEY (CD_PAUTA) REFERENCES PUBLIC.PAUTA(CD_PAUTA)
);
